### ISSUE TITLE
http://rickrolldb.com/ does not work!

### ISSUE THREAD

**Issue by mozkan007** [jamiew/rickrolldb#2]
Hi.I am using your filter in Ublock origin.However this filter can not be updated because of the filter site is not working.Please fix it.

**Comment by jamiew** [comment]
Looks like /ricklist.txt is misbehaving. Clearing the caches now

**Comment by jamiew** [comment]
It's back now: http://rickrolldb.com/ricklist.txt

I haven't tried using it with Ublock, let me know if it works.

FWIW this list is also not particularly up-to-date... rickrolls kind of a thing of the past?!?!
